const fs = require('fs');
const path = require('path');
const jsdoc2md = require('jsdoc-to-markdown');

/**
 * @module DocSync
 * @description Automatically generates API documentation from JSDoc comments within the bot's source code.
 */

/**
 * Generates Markdown documentation from JSDoc comments in the source files
 * and saves it to a file. This function is designed to be run during a build process
 * or on-demand to keep documentation synchronized with the codebase.
 *
 * @returns {Promise<void>} A promise that resolves when the documentation has been successfully generated.
 * @throws {Error} Throws an error if the documentation generation or file writing fails.
 */
async function updateDocs() {
  try {
    console.log('Starting documentation generation...');

    // Scan all .js files in the bot's src directory for JSDoc comments.
    const sourceFiles = path.join(__dirname, '*.js');
    
    // Define the output path for the generated markdown file.
    // This places the file in a 'docs' folder at the project root for easy access.
    const outputPath = path.join(__dirname, '..', '..', 'docs', 'bot-api.md');
    
    // Ensure the output directory exists before writing the file.
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    console.log(`Scanning files matching: ${sourceFiles}`);
    
    // Render the JSDoc comments into Markdown content.
    const docContent = await jsdoc2md.render({ files: sourceFiles });

    const finalMarkdown = `# Sentinel Bot API Documentation\n\n_This documentation is auto-generated from the source code. Do not edit this file directly._\n\n---\n\n${docContent}`;

    // Write the generated content to the output file.
    fs.writeFileSync(outputPath, finalMarkdown);

    console.log(`✅ Documentation successfully generated at: ${outputPath}`);

  } catch (error) {
    console.error('❌ Failed to generate documentation:', error);
    // Propagate the error to be handled by the caller.
    throw new Error('Documentation generation failed.');
  }
}

module.exports = { updateDocs };
